controller_manager:
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_gripper_controller:
      type: position_controllers/GripperActionController

    right_arm_gripper_controller:
      type: position_controllers/GripperActionController

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

left_arm_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - left_arm_shoulder_pan_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_joint
      - left_arm_wrist_1_joint
      - left_arm_wrist_2_joint
      - left_arm_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      left_arm_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      left_arm_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      left_arm_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      left_arm_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      left_arm_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      left_arm_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

right_arm_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_joint
      - right_arm_wrist_1_joint
      - right_arm_wrist_2_joint
      - right_arm_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      right_arm_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      right_arm_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      right_arm_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      right_arm_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      right_arm_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      right_arm_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

left_arm_gripper_controller:
  ros__parameters:
    type: position_controllers/GripperActionController
    joint: left_arm_robotiq_left_knuckle_joint
    action_monitor_rate: 20.0

right_arm_gripper_controller:
  ros__parameters:
    type: position_controllers/GripperActionController
    joint: right_arm_robotiq_left_knuckle_joint
    action_monitor_rate: 20.0

torso_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - torso_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      torso_yaw_joint: { trajectory: 0.2, goal: 0.1 }

head_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - neck_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      neck_pitch_joint: { trajectory: 0.2, goal: 0.1 }