controller_manager:
  ros__parameters:
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm1_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm2_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm1_gripper_controller:
      type: position_controllers/GripperActionController

    arm2_gripper_controller:
      type: position_controllers/GripperActionController

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

arm1_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - arm1_shoulder_pan_joint
      - arm1_shoulder_lift_joint
      - arm1_elbow_joint
      - arm1_wrist_1_joint
      - arm1_wrist_2_joint
      - arm1_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      arm1_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      arm1_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

arm2_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      arm2_shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_elbow_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      arm2_wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

arm1_gripper_controller:
  ros__parameters:
    type: position_controllers/GripperActionController
    joint: arm1_robotiq_left_knuckle_joint
    action_monitor_rate: 20.0

arm2_gripper_controller:
  ros__parameters:
    type: position_controllers/GripperActionController
    joint: arm2_robotiq_left_knuckle_joint
    action_monitor_rate: 20.0

torso_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - torso_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      torso_yaw_joint: { trajectory: 0.2, goal: 0.1 }

head_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - neck_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      neck_pitch_joint: { trajectory: 0.2, goal: 0.1 }