# Initial joint positions for simulation startup
initial_positions:
  left_arm_shoulder_pan_joint: 0.0
  left_arm_shoulder_lift_joint: -1.57
  left_arm_elbow_joint: 0.0
  left_arm_wrist_1_joint: -1.57
  left_arm_wrist_2_joint: 0.0
  left_arm_wrist_3_joint: 0.0
  right_arm_shoulder_pan_joint: 0.0
  right_arm_shoulder_lift_joint: -1.57
  right_arm_elbow_joint: 0.0
  right_arm_wrist_1_joint: -1.57
  right_arm_wrist_2_joint: 0.0
  right_arm_wrist_3_joint: 0.0
  left_arm_robotiq_left_knuckle_joint: 0.0
  right_arm_robotiq_left_knuckle_joint: 0.0
